<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
	"http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<title>Exemplo de Login</title>

		<link type="text/css" rel="stylesheet" href="/reset_clearfix.css">
		<link type="text/css" rel="stylesheet" href="/style.css">
	</head>
	<body>
        <div id="all">
			<h1><a href="/">Cesumar</a></h1>
			
<?php echo $this->layout()->content ?>

        </div>
    </body>
</html>

